#ifndef ARIB_STD_B25_ERROR_CODE_H
#define ARIB_STD_B25_ERROR_CODE_H

#define ARIB_STD_B25_ERROR_INVALID_PARAM         -1
#define ARIB_STD_B25_ERROR_NO_ENOUGH_MEMORY      -2
#define ARIB_STD_B25_ERROR_NON_TS_INPUT_STREAM   -3
#define ARIB_STD_B25_ERROR_NO_PAT_IN_HEAD_16M    -4
#define ARIB_STD_B25_ERROR_NO_PMT_IN_HEAD_32M    -5
#define ARIB_STD_B25_ERROR_NO_ECM_IN_HEAD_32M    -6
#define ARIB_STD_B25_ERROR_EMPTY_B_CAS_CARD      -7
#define ARIB_STD_B25_ERROR_INVALID_B_CAS_STATUS  -8
#define ARIB_STD_B25_ERROR_ECM_PROC_FAILURE      -9
#define ARIB_STD_B25_ERROR_DECRYPT_FAILURE      -10

#endif /* ARIB_STD_B25_ERROR_CODE_H */
